name: Restrict Feature to Main/Master Merges

on:
  pull_request:
    branches: [main, master, develop]

jobs:
  restrict-feature-to-master:
    name: restrict-feature-to-master    # This will appear in Rulesets as a required status check
    runs-on: ubuntu-latest

    steps:
      - name: Validate merge rules
        shell: bash
        run: |
          BASE="${{ github.base_ref }}"   # target branch
          HEAD="${{ github.head_ref }}"   # source branch

          echo "Target (base branch): $BASE"
          echo "Source (head branch):  $HEAD"

          # Block: feature/* -> main/master
          if [[ ("$BASE" == "main" || "$BASE" == "master") && "$HEAD" == feature/* ]]; then
            echo "❌ Forbidden: feature/* cannot be merged into main/master."
            exit 1
          fi

          echo "✔ Allowed merge."
          exit 0
